/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NvqBrandsNavbar {
    }
}
declare global {
    interface HTMLNvqBrandsNavbarElement extends Components.NvqBrandsNavbar, HTMLStencilElement {
    }
    var HTMLNvqBrandsNavbarElement: {
        prototype: HTMLNvqBrandsNavbarElement;
        new (): HTMLNvqBrandsNavbarElement;
    };
    interface HTMLElementTagNameMap {
        "nvq-brands-navbar": HTMLNvqBrandsNavbarElement;
    }
}
declare namespace LocalJSX {
    interface NvqBrandsNavbar {
    }
    interface IntrinsicElements {
        "nvq-brands-navbar": NvqBrandsNavbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nvq-brands-navbar": LocalJSX.NvqBrandsNavbar & JSXBase.HTMLAttributes<HTMLNvqBrandsNavbarElement>;
        }
    }
}
